# Generated by Django 6.0.7 on 2026-07-19 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_order', models.IntegerField(default=0, help_text='Order in which the event occurs in the show')),
                ('name', models.CharField(max_length=255)),
                ('score_type', models.CharField(choices=[('TIME', 'Time'), ('POINTS', 'Points')], max_length=10)),
                ('score_order', models.CharField(choices=[('ASC', 'Ascending (Lowest is best)'), ('DESC', 'Descending (Highest is best)')], max_length=10)),
                ('score_processor', models.CharField(choices=[('SUM', 'Sum'), ('AVG', 'Average'), ('MAX', 'Maximum')], max_length=10)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('show_number', models.IntegerField()),
                ('events', models.ManyToManyField(related_name='registered_contestants', to='core.event')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contestants', to='core.show')),
            ],
            options={
                'unique_together': {('show', 'show_number')},
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='core.contestant')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='core.event')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.show'),
        ),
    ]
