# Generated by Django 6.0.7 on 2026-07-19 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='is_tie_breaker',
            field=models.BooleanField(default=False),
        ),
    ]
