# Generated by Django 6.0.7 on 2026-07-20 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_score_is_tie_breaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='group_size',
            field=models.IntegerField(default=1, help_text='Number of contestants scored together (1 for individual)'),
        ),
    ]
