# Generated by Django 6.0.7 on 2026-07-20 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event_group_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestantGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Team Alpha' or 'Pair 1'", max_length=255)),
                ('events', models.ManyToManyField(related_name='registered_groups', to='core.event')),
                ('members', models.ManyToManyField(related_name='group_memberships', to='core.contestant')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contestant_groups', to='core.show')),
            ],
        ),
    ]
