# Generated by Django 6.0.7 on 2026-07-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contestantgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='score_order',
            field=models.CharField(choices=[('ASC', 'Ascending (Lowest is best)'), ('DESC', 'Descending (Highest is best)')], help_text='How to sort the results of multiple scores', max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='score_processor',
            field=models.CharField(choices=[('SUM', 'Sum'), ('AVG', 'Average'), ('MAX', 'Maximum')], help_text='How to combine multiple scores', max_length=10),
        ),
    ]
